### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [sticknanton/Checkers#1]
Nick, great job! Application works really well, looks great and you solved some of the issues you had mentioned regarding the moveable class. I also really like how you modeled the board as an array and then used that to control your logic as opposed to controlling your logic directly on the DOM. Separation of concerns is a great concept to get behind.

One thing I would love to see you work on is refactoring some of your logic to DRY it up a bit. How do you think you could approach this to clean up some repetition?

**Comment by ajhofferber** [comment]
Hey Nick,

Cool project! I really like what you were able to come up with. There's obviously a lot of logic behind this, and I appreciate that it gives a hint to non-checkers players (me) as to which spaces are available to be moved into. 

In addition to Avi's comments, I would LOVE to see you add some more to your README.md. Maybe explain the technologies you used and have some screen shots. It has such a pretty interface that it would be a shame for people looking through your repo to not get a chance to see what's going on.  Also you ought to include a link to your gh-pages version so EVERYONE can play!

Overall, really great stuff!  

Score: 3 (reference project markdown if curious about scoring)

-Ash
